name: lint_visitor_generator
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  analyzer: ">=6.2.0 <7.0.0"
  build: ^2.4.1
  build_config: ^1.1.1
  collection: ^1.17.1
  meta: ^1.11.0
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.1
  source_gen_test: ^1.0.6
